RUN --mount=type=tmpfs,target=/var/lib/dkms \
    --mount=type=bind,source=./mok.key,target=/var/lib/dkms/mok.key \
    --mount=type=bind,source=./files/system/etc/mok.pub,target=/var/lib/dkms/mok.pub \
    KERN=$(ls /usr/src/kernels | head --lines=1) && \
    dkms install $(ls -d /usr/src/evdi-*) -k $KERN && \
    dkms status
